import { useEffect, useState } from 'react'
import { ApiFailure, getJson, postJson } from './api'
type State = { handover_status?: string; archive_status?: string; signature_status?: string; line_results?: { line_no: number; status: string; error_message?: string }[] }
const labels: Record<string, string> = { NOT_SUBMITTED: '尚未提交', ACCEPTED: '已受理，待回查', PROCESSED: '全部处理成功', PARTIAL_PROCESSED: '部分成功，需处理失败条目', CANCELLED: '已撤销', NOT_ARCHIVED: '尚未归档', ARCHIVED: '已归档', UNSIGNED: '尚未签名', SIGNED: '模拟签名完成', PASSED: '预校验通过', BLOCKED: '被阻挡', FAILED: '处理失败' }
export function DemoDeliveryPanel({ contextId, instanceId, revisionId, confirmed, editable }: { contextId: string; instanceId: string; revisionId: string | null; confirmed: boolean; editable: boolean }) {
  const [state, setState] = useState<State | null>(null), [message, setMessage] = useState(''), [failure, setFailure] = useState(''), [busy, setBusy] = useState(false)
  const base = `/demo/contexts/${contextId}/instances/${instanceId}/delivery`
  useEffect(() => { const controller = new AbortController(); setState(null); setMessage(''); setFailure(''); void getJson<State>(base, controller.signal).then(value => { if (!controller.signal.aborted) setState(value) }).catch(error => { if (!controller.signal.aborted) setFailure(error.message) }); return () => controller.abort() }, [base, revisionId])
  const act = async (action: string) => { setBusy(true); setFailure(''); try { const value = await postJson<{ state: State; result: { validation_status?: string; handover_status?: string; archive_status?: string; signature_status?: string } }>(base + '/' + action, {}); setState(value.state); const status = (action === 'signature' ? value.result.signature_status : action === 'archive' ? value.result.archive_status : value.result.validation_status || value.result.handover_status) || ''; setMessage(labels[status] || status) } catch (error) { setFailure(error instanceof ApiFailure ? error.message : '模拟交付请求失败') } finally { setBusy(false) } }
  const disabled = busy || !confirmed || !editable
  return <section className="snapshot-facts"><h3>模拟医院交付</h3><p>当前演示提交 BC-001 的四条主治疗药。支持治疗、预处理和水化可在完整表单查看，本次演示交付未包含这些项目。</p><p>演示编码、数量和填写值均为虚构配置，未发送真实医院。</p>{!confirmed && <p>先保存并确认这次修订，再操作模拟医院。</p>}<div className="editor-footer-actions">{[['validate', '模拟预校验'], ['import', '模拟导入医嘱'], ['query', '回查医嘱结果'], ['archive', '模拟病历归档'], ['signature', '回查模拟签名'], ['cancel', '撤销模拟交付']].map(([action, label]) => <button key={action} disabled={disabled || (['archive', 'signature'].includes(action) && state?.handover_status !== 'PROCESSED') || (action === 'signature' && state?.archive_status !== 'ARCHIVED') || (['query', 'cancel'].includes(action) && (!state?.handover_status || state.handover_status === 'NOT_SUBMITTED')) || (action === 'cancel' && (state?.archive_status === 'ARCHIVED' || state?.handover_status === 'CANCELLED'))} onClick={() => act(action)}>{label}</button>)}</div>{message && <p role="status">{message}</p>}{failure && <p role="alert">{failure}</p>}{state && <><p>医嘱：{labels[state.handover_status || ''] || state.handover_status}　归档：{labels[state.archive_status || 'NOT_ARCHIVED']}　签名：{labels[state.signature_status || 'UNSIGNED']}</p>{state.line_results?.map(line => <p key={line.line_no}>第 {line.line_no} 条：{labels[line.status] || line.status}{line.error_message ? ' · ' + line.error_message : ''}</p>)}</>}</section>
}
